### ISSUE TITLE
How to Configure Multisite

### ISSUE THREAD

**Issue by liko28s** [dabapps/django-simple-robots#8]
Hi guys, currently we use django-simple-robots on a Multisite Django Project, we use these domains
```
a.mydomain.com
b.mydomain.com
c.mydomain.com
```
How can we enable django-simple-robots to allow multisite and generate separate robots.txt file for each domain?
can we set the `ROBOTS_ALLOW_HOST` environment variable to a space separated string with three domains?
```
ROBOTS_ALLOW_HOST= a.mydomain.com b.mydomain.com c.mydomain.com
```

**Comment by liko28s** [comment]
I figure out a Pull Request, please review and publish to pypi.

thanks

**Comment by j4mie** [comment]
See comment on #9
